### ISSUE TITLE
Dead links to CF templates on Getting Started with Fluentd

### ISSUE THREAD

**Issue by ali-maredia** [panther-labs/panther-docs#4]
In https://github.com/panther-labs/panther-docs/blob/main/docs/gitbook/guides/onboarding-with-fluentd/resource-guide.md, there are 2 GitHub links that no longer work:

https://github.com/panther-labs/panther-docs/blob/10e90e9cc926a5637bded91e5e0c5ef86370125f/docs/gitbook/guides/onboarding-with-fluentd/resource-guide.md#L34

https://github.com/panther-labs/panther-docs/blob/10e90e9cc926a5637bded91e5e0c5ef86370125f/docs/gitbook/guides/onboarding-with-fluentd/resource-guide.md#L57

This appears to be due to https://github.com/panther-labs/panther-auxiliary/pull/18 removing the files.

**Comment by 3nvi** [comment]
Templates have been reinstated via https://github.com/panther-labs/panther-auxiliary/pull/19

Thanks again
